spring.datasource.url=jdbc:mysql://root:ujWGPVJzweHczvGIvvickVrJfJZnJdBA@mysql.railway.internal:3306/railway
spring.datasource.username=${railway}
spring.datasource.password=${ujWGPVJzweHczvGIvvickVrJfJZnJdBA}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

pathshala.admin.secret-key=${Tushar@5436}